# Generated by Django 4.2.5 on 2023-09-16 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='indicator_name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndicatorsMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='metric_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='metric_description')),
                ('unit', models.CharField(max_length=200, verbose_name='metric_unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('indicator_metric_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicatorsmetric')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='public.test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=5, max_digits=10)),
                ('indicator_metric_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicatorsmetric')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='indicatorsmetric',
            name='metric_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.metric'),
        ),
    ]
